import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ja' | 'vi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'home': 'Home',
    'plan': 'Plan',
    'activity': 'Activity',
    'settings': 'Settings',
    'dashboard': 'Dashboard',
    'budget_overview': 'Budget Overview',
    'total_budget': 'Total Budget',
    'used': 'Used',
    'remaining': 'Remaining',
    'fund_registration': 'Fund Registration',
    'ideas': 'Ideas',
    'meetings': 'Meetings',
    'plan_input': 'Plan Input',
    'fund_about': 'About Fund Registration',
    'fund_about_desc': 'At the beginning of each fiscal year, register the approved budget amount. This amount will be the basis for activity budget for the year.',
    'edit_fund_registration': 'Edit Fund Registration',
    'no_fund_registration': 'No fund registration yet',
    'fiscal_year': 'Fiscal Year',
    'approved_amount': 'Approved Amount',
    'fund_source': 'Fund Source',
    'payment_date': 'Payment Date',
    'payer_name': 'Payer Name',
    'recorded_by': 'Recorded By',
    'approved': 'Approved',
    'activity_list': 'Activity List',
    'reporting': 'Reporting',
    'submit_activity_log': 'Submit Activity Log',
    'upload_receipt': 'Upload Receipt',
    'recent_uploads': 'Recent Uploads',
    'verified': 'Verified',
    'pending': 'Pending',
    'final_report': 'Final Report',
    'download_final_report': 'Download Final Report PDF',
    'create_final_report': 'Create Final Report PDF',
    'language': 'Language',
    'select_language': 'Select Language',
    'english': 'English',
    'japanese': 'Japanese',
    'vietnamese': 'Vietnamese',
    'save': 'Save',
    'cancel': 'Cancel',
    'back': 'Back',
    'submit': 'Submit',
    'loading': 'Loading...',
    'receipt_registration': 'Receipt Registration',
    'activity_log_registration': 'Activity Log Registration',
    'activity_info': 'Activity Information',
    'target_activity': 'Target Activity',
    'activity_date': 'Activity Date',
    'location': 'Location',
    'work_description': 'Work Description / Activity Log',
    'receipt_invoice': 'Receipt / Invoice',
    'add_item': 'Add Item',
    'expense_category': 'Expense Category',
    'vendor_name': 'Vendor Name',
    'invoice_number': 'Invoice Number',
    'amount': 'Amount',
    'total_amount': 'Total Amount',
    'submission_info': 'Submission Information',
    'submitter': 'Submitter',
    'submission_date': 'Submission Date',
    'submitting': 'Submitting...',
    'register': 'Register',
    'success_message': '✅ Successfully registered!',
    'error_message': 'Registration error occurred',
    'select_activity': 'Please select an activity',
    'no_approved_activities': 'No approved activities',
    'photo_upload_note': '💡 In the actual app, you can upload photos here',
    'cmb_only': 'This feature is only available for CMB members',
    'community_name': 'Ban Pho Village',
    'activities': 'Activities',
    'progress': 'Progress',
    'view_details': 'View Details',
    'completed': 'Completed',
    'budget': 'Budget',
    'no_activities': 'No activities for this year',
    'participants': 'Participants',
    'view_minutes': 'View Minutes',
    'scheduled': 'Scheduled',
    'community_budget_this_year': 'Community Budget This Year',
    'next_actions': 'Next Actions',
    'workflow': 'Workflow',
    'year': 'Year',
    'this_year': 'This Year',
    'plan_and_ideas': 'Plan & Ideas',
    'plan_and_ideas_subtitle': 'Activity planning and idea management',
    'new_idea': 'Submit New Idea',
    'selected': 'Selected',
    'under_review': 'Under Review',
    'submitted': 'Submitted',
    'not_selected': 'Not Selected',
    'submitter_label': 'Submitted by',
    'new_meeting': 'Create New Meeting',
    'chair': 'Chair',
    'planning_meeting': 'Planning Meeting',
    'budget_approval_meeting': 'Budget Approval Meeting',
    'quarterly_review': 'Quarterly Progress Review',
    'village_head': 'Village Head',
    'cmb_leader': 'CMB Leader',
    'forest_officer': 'Forest Officer',
    'planning_guide': 'Planning Guide',
    'planning_guide_desc': 'Create detailed activity plans based on selected ideas.',
    'create_new_plan': 'Create New Activity Plan',
    'created_plans': 'Created Plans',
    'budget_input': 'Budget Input',
    'activity_management': 'Activity Management',
    'forest_patrol': 'Forest Patrol and Protection',
    'ntfp_collection': 'NTFP Collection',
  },
  ja: {
    'home': 'ホーム',
    'plan': '計画',
    'activity': '活動',
    'settings': '設定',
    'dashboard': 'ダッシュボード',
    'budget_overview': '予算概要',
    'total_budget': '全体予算',
    'used': '使用済み',
    'remaining': '残額',
    'fund_registration': 'Fund登録',
    'ideas': 'アイデア',
    'meetings': '会議',
    'plan_input': '計画入力',
    'fund_about': 'Fund登録について',
    'fund_about_desc': '各年度の初めに、承認された予算額を登録します。この金額が、その年の活動予算の基準となります。',
    'edit_fund_registration': 'Fund登録情報を編集',
    'no_fund_registration': 'まだFund登録がありません',
    'fiscal_year': '年度',
    'approved_amount': '承認金額',
    'fund_source': '資金源',
    'payment_date': '支払日',
    'payer_name': '支払者',
    'recorded_by': '登録者',
    'approved': '承認済み',
    'activity_list': '活動一覧',
    'reporting': '報告・記録',
    'submit_activity_log': '活動記録を入力',
    'upload_receipt': 'レシート・写真をアップロード',
    'recent_uploads': '最近のアップロード',
    'verified': '確認済み',
    'pending': '確認待ち',
    'final_report': '最終報告書',
    'download_final_report': '最終報告書PDFをダウンロード',
    'create_final_report': '最終報告書PDFを作成',
    'language': '言語',
    'select_language': '言語を選択',
    'english': '英語',
    'japanese': '日本語',
    'vietnamese': 'ベトナム語',
    'save': '保存',
    'cancel': 'キャンセル',
    'back': '戻る',
    'submit': '登録する',
    'loading': '読み込み中...',
    'receipt_registration': 'レシート登録',
    'activity_log_registration': '活動ログ登録',
    'activity_info': '活動情報',
    'target_activity': '対象活動',
    'activity_date': '活動日',
    'location': '場所',
    'work_description': '作業内容・活動ログ',
    'receipt_invoice': 'レシート・領収書',
    'add_item': '項目追加',
    'expense_category': '支出カテゴリー',
    'vendor_name': '業者名',
    'invoice_number': '領収書番号',
    'amount': '金額',
    'total_amount': '合計金額',
    'submission_info': '提出情報',
    'submitter': '提出者',
    'submission_date': '提出日',
    'submitting': '登録中...',
    'register': '登録する',
    'success_message': '✅ 登録が完了しました！',
    'error_message': '登録エラーが発生しました',
    'select_activity': '活動を選択してください',
    'no_approved_activities': '承認された活動がありません',
    'photo_upload_note': '💡 実際のアプリでは、ここで写真をアップロードできます',
    'cmb_only': 'この機能はCMBメンバーのみ利用できます',
    'community_name': 'Ban Pho Village',
    'activities': '活動',
    'progress': '進捗度',
    'view_details': '詳細を見る',
    'completed': '完了',
    'budget': '予算',
    'no_activities': 'この年度の活動はありません',
    'participants': '参加者',
    'view_minutes': '議事録を見る',
    'scheduled': '予定',
    'community_budget_this_year': '今年のコミュニティの予算',
    'next_actions': '次のアクション',
    'workflow': 'ワークフロー',
    'year': '年度',
    'this_year': '今年',
    'plan_and_ideas': '計画・アイデア',
    'plan_and_ideas_subtitle': '活動の計画とアイデア管理',
    'new_idea': '新しいアイデアを提出',
    'selected': '選ばれた',
    'under_review': '検討中',
    'submitted': '提出済み',
    'not_selected': '選ばれなかった',
    'submitter_label': '提出者',
    'new_meeting': '新しい会議を設定',
    'chair': '議長',
    'planning_meeting': '活動計画会議',
    'budget_approval_meeting': '予算承認会議',
    'quarterly_review': '第3四半期進捗レビュー',
    'village_head': '村長',
    'cmb_leader': 'CMBリーダー',
    'forest_officer': '森林官',
    'planning_guide': '計画作成ガイド',
    'planning_guide_desc': '選ばれたアイデアに基づいて、詳しい活動計画を作成します。',
    'create_new_plan': '新しい活動計画を作成',
    'created_plans': '作成済みの計画',
    'budget_input': '予算入力中',
    'activity_management': '活動管理',
    'forest_patrol': '森林パトロール・保護活動',
    'ntfp_collection': '非木材林産物の採取',
  },
  vi: {
    'home': 'Trang chủ',
    'plan': 'Kế hoạch',
    'activity': 'Hoạt động',
    'settings': 'Cài đặt',
    'dashboard': 'Bảng điều khiển',
    'budget_overview': 'Tổng quan ngân sách',
    'total_budget': 'Tổng ngân sách',
    'used': 'Đã sử dụng',
    'remaining': 'Còn lại',
    'fund_registration': 'Đăng ký Quỹ',
    'ideas': 'Ý tưởng',
    'meetings': 'Cuộc họp',
    'plan_input': 'Nhập kế hoạch',
    'fund_about': 'Về Đăng ký Quỹ',
    'fund_about_desc': 'Vào đầu mỗi năm tài chính, đăng ký số tiền ngân sách được phê duyệt. Số tiền này sẽ là cơ sở cho ngân sách hoạt động của năm.',
    'edit_fund_registration': 'Chỉnh sửa Đăng ký Quỹ',
    'no_fund_registration': 'Chưa có đăng ký quỹ',
    'fiscal_year': 'Năm tài chính',
    'approved_amount': 'Số tiền được phê duyệt',
    'fund_source': 'Nguồn quỹ',
    'payment_date': 'Ngày thanh toán',
    'payer_name': 'Người thanh toán',
    'recorded_by': 'Được ghi bởi',
    'approved': 'Đã phê duyệt',
    'activity_list': 'Danh sách hoạt động',
    'reporting': 'Báo cáo & Ghi chép',
    'submit_activity_log': 'Nhập nhật ký hoạt động',
    'upload_receipt': 'Tải lên biên lai & ảnh',
    'recent_uploads': 'Tải lên gần đây',
    'verified': 'Đã xác minh',
    'pending': 'Đang chờ',
    'final_report': 'Báo cáo cuối kỳ',
    'download_final_report': 'Tải xuống Báo cáo cuối kỳ PDF',
    'create_final_report': 'Tạo Báo cáo cuối kỳ PDF',
    'language': 'Ngôn ngữ',
    'select_language': 'Chọn ngôn ngữ',
    'english': 'Tiếng Anh',
    'japanese': 'Tiếng Nhật',
    'vietnamese': 'Tiếng Việt',
    'save': 'Lưu',
    'cancel': 'Hủy',
    'back': 'Quay lại',
    'submit': 'Đăng ký',
    'loading': 'Đang tải...',
    'receipt_registration': 'Đăng ký biên lai',
    'activity_log_registration': 'Đăng ký nhật ký hoạt động',
    'activity_info': 'Thông tin hoạt động',
    'target_activity': 'Hoạt động mục tiêu',
    'activity_date': 'Ngày hoạt động',
    'location': 'Địa điểm',
    'work_description': 'Mô tả công việc / Nhật ký hoạt động',
    'receipt_invoice': 'Biên lai / Hóa đơn',
    'add_item': 'Thêm mục',
    'expense_category': 'Danh mục chi phí',
    'vendor_name': 'Tên nhà cung cấp',
    'invoice_number': 'Số hóa đơn',
    'amount': 'Số tiền',
    'total_amount': 'Tổng số tiền',
    'submission_info': 'Thông tin gửi',
    'submitter': 'Người gửi',
    'submission_date': 'Ngày gửi',
    'submitting': 'Đang gửi...',
    'register': 'Đăng ký',
    'success_message': '✅ Đăng ký thành công!',
    'error_message': 'Đã xảy ra lỗi đăng ký',
    'select_activity': 'Vui lòng chọn hoạt động',
    'no_approved_activities': 'Không có hoạt động được phê duyệt',
    'photo_upload_note': '💡 Trong ứng dụng thực tế, bạn có thể tải lên ảnh tại đây',
    'cmb_only': 'Tính năng này chỉ dành cho thành viên CMB',
    'community_name': 'Làng Ban Pho',
    'activities': 'Hoạt động',
    'progress': 'Tiến độ',
    'view_details': 'Xem chi tiết',
    'completed': 'Hoàn thành',
    'budget': 'Ngân sách',
    'no_activities': 'Không có hoạt động nào trong năm này',
    'participants': 'Người tham gia',
    'view_minutes': 'Xem biên bản',
    'scheduled': 'Đã lên lịch',
    'community_budget_this_year': 'Ngân sách cộng đồng năm nay',
    'next_actions': 'Hành động tiếp theo',
    'workflow': 'Quy trình',
    'year': 'Năm',
    'this_year': 'Năm nay',
    'plan_and_ideas': 'Kế hoạch & Ý tưởng',
    'plan_and_ideas_subtitle': 'Lập kế hoạch hoạt động và quản lý ý tưởng',
    'new_idea': 'Gửi ý tưởng mới',
    'selected': 'Đã chọn',
    'under_review': 'Đang xem xét',
    'submitted': 'Đã gửi',
    'not_selected': 'Không được chọn',
    'submitter_label': 'Người gửi',
    'new_meeting': 'Tạo cuộc họp mới',
    'chair': 'Chủ tọa',
    'planning_meeting': 'Cuộc họp kế hoạch',
    'budget_approval_meeting': 'Cuộc họp phê duyệt ngân sách',
    'quarterly_review': 'Đánh giá tiến độ quý 3',
    'village_head': 'Trưởng làng',
    'cmb_leader': 'Trưởng nhóm CMB',
    'forest_officer': 'Cán bộ kiểm lâm',
    'planning_guide': 'Hướng dẫn lập kế hoạch',
    'planning_guide_desc': 'Tạo kế hoạch hoạt động chi tiết dựa trên các ý tưởng đã chọn.',
    'create_new_plan': 'Tạo kế hoạch hoạt động mới',
    'created_plans': 'Các kế hoạch đã tạo',
    'budget_input': 'Đang nhập ngân sách',
    'activity_management': 'Quản lý hoạt động',
    'forest_patrol': 'Tuần tra và bảo vệ rừng',
    'ntfp_collection': 'Thu thập sản phẩm lâm sản ngoài gỗ',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'ja';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
